<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Wybierz opcjSMLXLXXL</name>
   <tag></tag>
   <elementGuidId>47dadf4d-93df-411f-b4b0-5361e76eec16</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='pa_rozmiar']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#pa_rozmiar</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>73bf5ec1-5065-418b-bc7a-cad82063cbe2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pa_rozmiar</value>
      <webElementGuid>4de6091f-b345-493e-83f6-c53116b96c3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>attribute_pa_rozmiar</value>
      <webElementGuid>0ea33f1f-9928-47ec-9cbc-10b3032998b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-attribute_name</name>
      <type>Main</type>
      <value>attribute_pa_rozmiar</value>
      <webElementGuid>4ef3951c-4d47-44b0-a05b-f16a2901584c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-show_option_none</name>
      <type>Main</type>
      <value>yes</value>
      <webElementGuid>694fc395-dcdf-44b4-8818-c44c282f85f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Wybierz opcjęSMLXLXXL</value>
      <webElementGuid>91390074-e0df-4871-8ea8-935ffa281894</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pa_rozmiar&quot;)</value>
      <webElementGuid>8e22cada-8a5f-4179-8bc3-ee1523cbf309</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='pa_rozmiar']</value>
      <webElementGuid>355116b3-3109-408c-9bca-60b4dd7a231a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='product-10876']/div[2]/form/table/tbody/tr[2]/td/select</value>
      <webElementGuid>a80bd767-8ed4-4003-99b1-c28f1fb033b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rozmiar'])[1]/following::select[1]</value>
      <webElementGuid>67040d45-2f6f-4fab-bcff-2d4abebaa028</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kolor'])[1]/following::select[2]</value>
      <webElementGuid>5cb5460b-d72f-4f5a-8e0e-11efb91ed4e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ilość Bluza z kapturem'])[1]/preceding::select[1]</value>
      <webElementGuid>c1065fcf-bfff-45f8-b7d1-a43f2506dba7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dodaj do koszyka'])[1]/preceding::select[1]</value>
      <webElementGuid>f55f4f59-e596-40d5-b6b4-c89f37aa2cca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/select</value>
      <webElementGuid>46604a11-76e6-4003-b7ce-3167cd2bc702</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'pa_rozmiar' and @name = 'attribute_pa_rozmiar' and (text() = 'Wybierz opcjęSMLXLXXL' or . = 'Wybierz opcjęSMLXLXXL')]</value>
      <webElementGuid>3397075b-12c8-4b00-96f1-fc352548a039</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
