<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Wybierz opcjBordowyGranatowy</name>
   <tag></tag>
   <elementGuidId>ea4306d0-32eb-4538-9b3b-8b6d66c259f0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='pa_kolor']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#pa_kolor</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>56ebbb70-f885-4928-9a25-d5d9c9c2dc35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pa_kolor</value>
      <webElementGuid>745890f7-2689-45d3-8cde-fa66b52698c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>attribute_pa_kolor</value>
      <webElementGuid>411d7ddb-31b4-42f8-b385-32785fce3bf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-attribute_name</name>
      <type>Main</type>
      <value>attribute_pa_kolor</value>
      <webElementGuid>3221332b-f9ac-4246-aa5c-f17a3ed75b2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-show_option_none</name>
      <type>Main</type>
      <value>yes</value>
      <webElementGuid>635364e6-aafb-466d-a24e-888f9b9bcc4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Wybierz opcjęBordowyGranatowy</value>
      <webElementGuid>56b54427-7fc0-4356-ab8d-c5dfa900a3ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pa_kolor&quot;)</value>
      <webElementGuid>5a7b944c-61b1-4a90-8236-b5b0441a91ba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='pa_kolor']</value>
      <webElementGuid>b21bfe0e-dee9-4ac8-87bf-c4244f66c3bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='product-10876']/div[2]/form/table/tbody/tr/td/select</value>
      <webElementGuid>44ad477a-3dfd-4410-9c0d-938a0d195f37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kolor'])[1]/following::select[1]</value>
      <webElementGuid>c704a201-33f7-4019-a3b5-f32750d262a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='kangurek'])[1]/following::select[1]</value>
      <webElementGuid>e8b14fe0-1581-4315-b587-c493af3c76d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rozmiar'])[1]/preceding::select[1]</value>
      <webElementGuid>1352b418-2364-4cc6-acec-1aa8d9c1c7a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ilość Bluza z kapturem'])[1]/preceding::select[2]</value>
      <webElementGuid>5c784c50-b913-4876-8276-117d7d058fdd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>00fbf106-b385-4a99-8b1c-129f82bfa89e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'pa_kolor' and @name = 'attribute_pa_kolor' and (text() = 'Wybierz opcjęBordowyGranatowy' or . = 'Wybierz opcjęBordowyGranatowy')]</value>
      <webElementGuid>b64f61a7-01db-4ae4-a85c-b0ffda18eb99</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
