<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Dodaj do koszyka</name>
   <tag></tag>
   <elementGuidId>d749e890-4b89-4ad1-bf57-9fe55460e5a5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.button.product_type_simple.add_to_cart_button.ajax_add_to_cart</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main']/ul/li/a[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7041bbc2-0d14-4d21-bf90-deda0ed86492</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>?add-to-cart=10362</value>
      <webElementGuid>348b4c58-937b-4a9b-88f2-05c803591a0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-quantity</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>d32e3df8-7661-4b9c-b8f8-6075ca330b29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button product_type_simple add_to_cart_button ajax_add_to_cart</value>
      <webElementGuid>704d196b-659b-4283-b3dd-f6b841687a24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-product_id</name>
      <type>Main</type>
      <value>10362</value>
      <webElementGuid>1e06389d-7247-47f2-a708-c52a866639c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Dodaj „Kubek PW” do koszyka</value>
      <webElementGuid>7d0dd7d3-e4c3-444d-b9ba-6409e549a136</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>nofollow</value>
      <webElementGuid>5ccac9cb-2d01-418c-9c92-e46faf4d9124</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Dodaj do koszyka</value>
      <webElementGuid>a54b7792-afe6-4fc8-a8b5-a997e3ab0f06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/ul[@class=&quot;products columns-3&quot;]/li[@class=&quot;product type-product post-10362 status-publish first instock product_cat-kubki product_cat-odziez-gadzety has-post-thumbnail featured taxable shipping-taxable purchasable product-type-simple&quot;]/a[@class=&quot;button product_type_simple add_to_cart_button ajax_add_to_cart&quot;]</value>
      <webElementGuid>5d4bf805-5e01-4df6-a204-799e879ac4b0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main']/ul/li/a[2]</value>
      <webElementGuid>1b8151f2-ec07-4881-931f-9d958d457b7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Dodaj do koszyka')]</value>
      <webElementGuid>df3dc5a7-cbfb-4589-afa4-28db5a997f43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='z VAT'])[1]/following::a[1]</value>
      <webElementGuid>e8498446-3c09-40ec-af9a-c8865a3116c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='zł'])[2]/following::a[1]</value>
      <webElementGuid>729f291d-36e3-4b71-9f25-4b9b253d8e72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kubek Grand'])[1]/preceding::a[1]</value>
      <webElementGuid>d4ca0ae0-9163-4a52-9263-5ab002a09a6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='zł'])[3]/preceding::a[1]</value>
      <webElementGuid>3125e1ba-68c0-4d14-bb7c-8dc7f3077a38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Dodaj do koszyka']/parent::*</value>
      <webElementGuid>12ae99df-7acb-4345-ba97-3b9a694f4b84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '?add-to-cart=10362')]</value>
      <webElementGuid>05e380e0-3cd0-46b6-bed0-d5f26a0eed83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/a[2]</value>
      <webElementGuid>38a3f3a0-db98-4115-a192-fb691d289197</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '?add-to-cart=10362' and (text() = 'Dodaj do koszyka' or . = 'Dodaj do koszyka')]</value>
      <webElementGuid>aea9d065-0e05-445a-8e0c-a15ec8badbc7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
