<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Wyloguj si</name>
   <tag></tag>
   <elementGuidId>a4fc7752-2b67-497a-ac11-eb6b755b3030</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//article[@id='post-8']/div/div/div/p/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3f12861d-a793-4f4e-86e2-fb8c7cb4c739</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.sklep.pw.edu.pl/moje-konto/customer-logout?_wpnonce=2b524990e4</value>
      <webElementGuid>f6efe8e8-f51d-46f5-b4b5-d1060fd76549</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Wyloguj się</value>
      <webElementGuid>47c581c9-411e-4378-a2f0-4e461423a8fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;post-8&quot;)/div[@class=&quot;entry-content&quot;]/div[@class=&quot;woocommerce&quot;]/div[@class=&quot;woocommerce-MyAccount-content&quot;]/p[1]/a[1]</value>
      <webElementGuid>c9903180-faa1-407c-b774-cfeffe9b037f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='post-8']/div/div/div/p/a</value>
      <webElementGuid>9bbf576d-59ae-42ce-a019-8f25fdbba380</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Wyloguj się')])[2]</value>
      <webElementGuid>53ecdfa5-f372-49e7-bc03-dae8927e323c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='konto_test_do_pracy_inz'])[2]/following::a[1]</value>
      <webElementGuid>c73ab680-5f24-42e5-8fc6-7abff4006583</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='konto_test_do_pracy_inz'])[1]/following::a[1]</value>
      <webElementGuid>38a600f3-b7b0-447b-ac30-21eef1862cf8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ostatnie zamówienia'])[1]/preceding::a[1]</value>
      <webElementGuid>4447c6d9-8ed6-43f9-ac5c-40f96b4b7e42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='adresami płatności i dostawy'])[1]/preceding::a[2]</value>
      <webElementGuid>c139479b-491c-426d-b455-d1e5e933d94d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://www.sklep.pw.edu.pl/moje-konto/customer-logout?_wpnonce=2b524990e4')])[2]</value>
      <webElementGuid>9a174d55-bcf4-4c50-b424-952937ceed05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/a</value>
      <webElementGuid>2b477ff8-7da5-4bdd-891a-a6003eb59aeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.sklep.pw.edu.pl/moje-konto/customer-logout?_wpnonce=2b524990e4' and (text() = 'Wyloguj się' or . = 'Wyloguj się')]</value>
      <webElementGuid>32fc5621-d391-4cd5-a6a2-705504ff4159</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
