<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ol__flex-control-nav flex-control-thumbs</name>
   <tag></tag>
   <elementGuidId>fd979504-ef2f-470e-9243-12aa957269c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='product-1776']/div/ol</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>ol.flex-control-nav.flex-control-thumbs</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ol</value>
      <webElementGuid>c1152e95-fcf6-44de-8262-fdbc79aae3f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex-control-nav flex-control-thumbs</value>
      <webElementGuid>bb2a7015-6235-4211-8ea2-3b152ebf3fc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product-1776&quot;)/div[@class=&quot;woocommerce-product-gallery woocommerce-product-gallery--with-images woocommerce-product-gallery--columns-5 images&quot;]/ol[@class=&quot;flex-control-nav flex-control-thumbs&quot;]</value>
      <webElementGuid>f66ab613-a38d-45b8-9cf9-cac81c8ca30d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='product-1776']/div/ol</value>
      <webElementGuid>da99a986-6cbb-4e41-b757-7d583fd1ba00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='/'])[4]/following::ol[1]</value>
      <webElementGuid>f2285b05-faa9-4ad5-bd84-4ceab8103bc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wyprzedaż'])[1]/following::ol[1]</value>
      <webElementGuid>fe552b58-4f64-46eb-94fd-881d65dccb62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bluza bejsbolówka'])[1]/preceding::ol[1]</value>
      <webElementGuid>591320a3-d7b3-49ac-a42c-5cb61032431a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='zł'])[2]/preceding::ol[1]</value>
      <webElementGuid>b229a12c-0207-4450-8c05-bb8ee8a3b0b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ol</value>
      <webElementGuid>28594e7c-08a1-450f-a406-871f429fed20</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
