<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Wybierz opcjMLXL</name>
   <tag></tag>
   <elementGuidId>b2104100-5760-44a5-bd4c-73bb78374101</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pa_rozmiar</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='pa_rozmiar']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>df570519-a523-44af-a902-0492ea186ad2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pa_rozmiar</value>
      <webElementGuid>989c83c8-ca55-4c4d-ac79-215ca304441b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>attribute_pa_rozmiar</value>
      <webElementGuid>8a7ba7dd-9378-4005-a73b-398788f40d6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-attribute_name</name>
      <type>Main</type>
      <value>attribute_pa_rozmiar</value>
      <webElementGuid>f0bbd086-4965-4a5e-bd16-21fe9b368f4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-show_option_none</name>
      <type>Main</type>
      <value>yes</value>
      <webElementGuid>8a82ff5d-427f-4fa6-8035-32085396d1c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Wybierz opcjęMLXL</value>
      <webElementGuid>cb0a6587-b797-4b4f-b87b-5ee0c32c9be7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pa_rozmiar&quot;)</value>
      <webElementGuid>a44c3851-23dd-4b98-8b41-ca2222c34619</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='pa_rozmiar']</value>
      <webElementGuid>2484768a-dbf8-4fa8-aa6c-a0ad536eb683</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='product-1776']/div[2]/form/table/tbody/tr[2]/td/select</value>
      <webElementGuid>a67a841e-b41c-47b4-808e-8785064d7e7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rozmiar'])[1]/following::select[1]</value>
      <webElementGuid>bdd9b12d-3388-4267-b47c-f1475e895a62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rodzaj'])[1]/following::select[2]</value>
      <webElementGuid>e3579687-c1f4-4968-bdc9-0d43ca48fe68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ilość Bluza bejsbolówka'])[1]/preceding::select[1]</value>
      <webElementGuid>1d794895-0baa-41c4-b29d-2ae9b7c8b1a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dodaj do koszyka'])[1]/preceding::select[1]</value>
      <webElementGuid>4147d9ec-6e4d-49af-b9d5-4636d969a825</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/select</value>
      <webElementGuid>db9508f6-14aa-42ac-83d6-2105d1b372a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'pa_rozmiar' and @name = 'attribute_pa_rozmiar' and (text() = 'Wybierz opcjęMLXL' or . = 'Wybierz opcjęMLXL')]</value>
      <webElementGuid>d0999ed0-f992-468e-b07c-598272cd2581</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
