<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Wybierz opcjDamskaMska</name>
   <tag></tag>
   <elementGuidId>98fc91ee-5c72-4113-a860-55c639135d91</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pa_rodzaj</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='pa_rodzaj']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>2027bc77-3d7e-4994-bc41-40385d64a0af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pa_rodzaj</value>
      <webElementGuid>02ca1447-c229-47c6-bb60-69f16fa40d42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>attribute_pa_rodzaj</value>
      <webElementGuid>bd1066ee-9744-462c-9fcf-84ea48fef43f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-attribute_name</name>
      <type>Main</type>
      <value>attribute_pa_rodzaj</value>
      <webElementGuid>bdf5518b-15ae-41d2-a703-f063da46124f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-show_option_none</name>
      <type>Main</type>
      <value>yes</value>
      <webElementGuid>93977b39-14ab-4faf-93f3-4662f4b93bc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Wybierz opcjęDamskaMęska</value>
      <webElementGuid>5e6c8bdf-59d2-4e28-9902-9ba39361114a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pa_rodzaj&quot;)</value>
      <webElementGuid>98890848-20d5-4c41-b5e4-01a3d9c4eae4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='pa_rodzaj']</value>
      <webElementGuid>89a0e9ab-092e-44c6-ab63-44db90e907eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='product-1776']/div[2]/form/table/tbody/tr/td/select</value>
      <webElementGuid>5a2bf07f-41c1-482a-a5a0-6df6004ba1f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rodzaj'])[1]/following::select[1]</value>
      <webElementGuid>44dcc896-6399-48c6-ab08-3016c5f35a26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='z VAT'])[1]/following::select[1]</value>
      <webElementGuid>f1ea9489-63a9-47fb-a40d-befc3611bfd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rozmiar'])[1]/preceding::select[1]</value>
      <webElementGuid>26a9f335-971e-48e3-a21a-3c68a036e94d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ilość Bluza bejsbolówka'])[1]/preceding::select[2]</value>
      <webElementGuid>e1c8c6ed-5416-4029-ae52-c916ce4491d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>1326533c-d8c2-4484-932c-7dc8fabcb1b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'pa_rodzaj' and @name = 'attribute_pa_rodzaj' and (text() = 'Wybierz opcjęDamskaMęska' or . = 'Wybierz opcjęDamskaMęska')]</value>
      <webElementGuid>1258044c-656a-41fa-9987-232fd165f1cb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
